version: '3.8'

services:
  # Finansier Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finansier-app
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
      PORT: 9000
      MONGO_URL: ${MONGO_URL}
    volumes:
      - ./logs:/app/logs
